name: 'Jekyll Minimal Action'
author: 'Vivien Richter <vivien-richter@outlook.de>'
description: 'Pure minimal Jekyll pipeline for universal usage.'
inputs:
  command:
    description: 'Complete Jekyll command'
    required: true
    default: 'jekyll --help'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
branding:
  icon: 'book-open'
  color: 'red'
